sudo: required
services:
  - docker

before_install:
  - docker build -t voltozavr/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true voltozavr/react-test npm test

after_success:
  - docker build -t voltozavr/fib-client ./client
  - docker build -t voltozavr/fib-nginx ./nginx
  - docker build -t voltozavr/fib-server ./server
  - docker build -t voltozavr/fib-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push voltozavr/fib-client
  - docker push voltozavr/fib-nginx
  - docker push voltozavr/fib-server
  - docker push voltozavr/fib-worker